### ISSUE TITLE
CVE found in releases prior to 3.5.4

### ISSUE THREAD

**Issue by a11apurva** [akimd/bison#44]
Apologies if this is not the right platform to ask this.

As you might be aware a CVE in bison has been found in releases prior to 3.5.4.

> GNU Bison before 3.5.4 allows attackers to cause a denial of service (application crash).

Does this vulnerability gets introduced to the application/binary which we build using Bison? (It is not very clear from the vulnerability description)

If yes, any idea where can I get a 3.5.4+ executable available for Windows?

Thanks!

**Comment by akimd** [comment]
Hi,

> As you might be aware a CVE in bison has been found in releases prior to 3.5.4.

I was not, thanks for reporting this.  The CVE is [here](https://nvd.nist.gov/vuln/detail/CVE-2020-14150).  I don't see the point of making a CVE for this, but...

> Does this vulnerability gets introduced to the application/binary which we build using Bison? (It is not very clear from the vulnerability description)

No, it's only bison itself that could be fed junk bad enough for it to crash.

> If yes, any idea where can I get a 3.5.4+ executable available for Windows?

Sorry, nope :(  Have a look at Chocolatey, and maybe Conan.

Cheers!

**Comment by a11apurva** [comment]
Hi @akimd, just to let you know about a new CVE -

https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bison

**Comment by akimd** [comment]
For the records, the CVEs have been requalified since then:

- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14150
 now reads:
 GNU Bison before 3.5.4 allows attackers to cause a denial of service (application crash). NOTE: there is a risk only if Bison is used with untrusted input, and an observed bug happens to cause unsafe behavior with a specific compiler/architecture. The bug reports were intended to show that a crash may occur in Bison itself, not that a crash may occur in code that is generated by Bison.

- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-24240
 now reads:
 GNU Bison before 3.7.1 has a use-after-free in _obstack_free in lib/obstack.c (called from gram_lex) when a '\0' byte is encountered. NOTE: there is a risk only if Bison is used with untrusted input, and the observed bug happens to cause unsafe behavior with a specific compiler/architecture. The bug report was intended to show that a crash may occur in Bison itself, not that a crash may occur in code that is generated by Bison.

**Comment by a11apurva** [comment]
Hi @akimd , since then a couple of more CVEs are published. Are these also closed in the latest 3.7.2 release?

> -  https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-24979
>  
>    A Buffer Overflow vulnerability was found in src/symtab.c in GNU bison 3.7.1.1-cb7dc-dirty. A local attacker may execute bison with crafted input file redefining the EOF token, which could triggers Heap buffer overflow and thus cause system crash.
> 
> - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-24980
> 
>   An assertion failure was found in src/parse-gram.c in GNU bison 3.7.1.1-cb7dc-dirty. A local attacker may execute bison with - crafted input file containing character '\' at the end and while still in a character or a string.

**Comment by akimd** [comment]
> Are these also closed in the latest 3.7.2 release?

Yes, they are.  And both of them, again, are not about the generated parsers.

**Comment by tcullum-rh** [comment]
@akimd  . I'm trying to figure out which actual code issue corresponds to CVE-2020-14150. Looking at https://github.com/akimd/bison/search?q=ahcheong&type=commits or just doing git log for that, I see 3 separate commits. But I believe any of them could cause a crash and thus I cannot tell which of these issues is actually that particular CVE - the CVE reference just links to the general release notes. Looks like Ahcheong reported assertion failure and segfault, both of which could cause a crash.

Thanks.
